//! Replays rough.js's own output against the Rust port.
//!
//! Fixtures are generated by `engine/tools/rough-oracle` from roughjs 4.6.4 — the exact
//! version Excalidraw pins — and committed, so this test needs neither Node nor a
//! network. Regenerate with `make oracle-fixtures`, which you should only need when the
//! pin in `scripts/oracle-sha.txt` moves.
//!
//! # Two fixtures, checking different things
//!
//! - `curated.json` carries **full ops** for a representative subset. This is the
//!   debugging surface: a failure names the operand of the op that moved.
//! - `sweep.summary.json` reduces the whole sweep (~1.4M ops) to a structural
//!   signature plus numeric aggregates. Broad coverage without 136MB in git.
//!
//! The signature hashes op **kinds only**, never coordinates. Hashing floats would
//! flake: a coordinate sitting within a last-ulp of a quantisation boundary lands in a
//! different bucket, and over 1.4M coordinates that is a near-certainty rather than a
//! risk. Structure is exact and hashes cleanly; magnitudes are checked as sums against
//! a relative tolerance instead.
//!
//! # The bar
//!
//! - **Structure is exact.** Same op kinds, count and order. A mismatch is a logic
//!   error, never a rounding one.
//! - **Coordinates within `1e-9`.** `+ - * /` and `sqrt` are exactly specified by
//!   IEEE-754 and agree bit-for-bit between V8 and Rust; `sin`, `cos` and friends are
//!   not, and may differ in the last ulp.

use std::collections::BTreeMap;

use draw_rough::generator;
use draw_rough::ops::{Op, OpSet, OpSetKind};
use draw_rough::options::{Ctx, FillStyle, Options};
use draw_rough::renderer;
use serde::Deserialize;

/// Coordinates may differ only by transcendental last-ulp error.
const TOLERANCE: f64 = 1e-9;

/// Aggregates are sums over thousands of coordinates, so error accumulates; they are
/// compared relative to magnitude rather than absolutely.
const RELATIVE_TOLERANCE: f64 = 1e-9;

// ---------------------------------------------------------------------------
// Fixture shapes
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct CuratedFixture {
    roughjs: String,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct SweepFixture {
    roughjs: String,
    cases: Vec<SweepCase>,
}

#[derive(Deserialize)]
struct Case {
    #[serde(rename = "fn")]
    func: String,
    args: serde_json::Value,
    options: JsOptions,
    #[serde(default)]
    opset: Option<JsOpSet>,
    #[serde(default)]
    sets: Option<Vec<JsOpSet>>,
    #[serde(default)]
    params: Option<JsEllipseParams>,
    #[serde(default)]
    segments: Option<Vec<JsSegment>>,
}

/// A normalized path segment as `path-data-parser` emits it.
#[derive(Deserialize, Clone)]
struct JsSegment {
    key: String,
    data: Vec<f64>,
}

fn segments(js: &[JsSegment]) -> Vec<renderer::Segment> {
    js.iter()
        .map(|s| match s.key.as_str() {
            "M" => renderer::Segment::MoveTo([s.data[0], s.data[1]]),
            "L" => renderer::Segment::LineTo([s.data[0], s.data[1]]),
            "C" => renderer::Segment::CurveTo([
                s.data[0], s.data[1], s.data[2], s.data[3], s.data[4], s.data[5],
            ]),
            "Z" => renderer::Segment::Close,
            other => panic!("normalize() should not emit {other}"),
        })
        .collect()
}

impl Case {
    /// A renderer case yields one op set, a generator drawable yields several.
    fn expected(&self) -> Vec<&JsOpSet> {
        match (&self.sets, &self.opset) {
            (Some(sets), _) => sets.iter().collect(),
            (None, Some(one)) => vec![one],
            (None, None) => panic!("fixture case has neither `sets` nor `opset`"),
        }
    }
}

#[derive(Deserialize)]
struct SweepCase {
    #[serde(rename = "fn")]
    func: String,
    args: serde_json::Value,
    options: JsOptions,
    #[serde(default)]
    params: Option<JsEllipseParams>,
    #[serde(default)]
    segments: Option<Vec<JsSegment>>,
    summary: Vec<JsSummary>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct JsSummary {
    #[serde(rename = "type")]
    kind: String,
    op_count: usize,
    kind_hash: u32,
    sum: f64,
    sum_abs: f64,
    max_abs: f64,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct JsOptions {
    max_randomness_offset: f64,
    roughness: f64,
    bowing: f64,
    stroke_width: f64,
    curve_tightness: f64,
    curve_fitting: f64,
    curve_step_count: f64,
    fill_style: String,
    fill_weight: f64,
    hachure_angle: f64,
    hachure_gap: f64,
    dash_offset: f64,
    dash_gap: f64,
    zigzag_offset: f64,
    seed: i64,
    disable_multi_stroke: bool,
    disable_multi_stroke_fill: bool,
    preserve_vertices: bool,
    fill_shape_roughness_gain: f64,
    #[serde(default)]
    fill: Option<String>,
}

#[derive(Deserialize)]
struct JsEllipseParams {
    increment: f64,
    rx: f64,
    ry: f64,
}

#[derive(Deserialize)]
struct JsOpSet {
    #[serde(rename = "type")]
    kind: String,
    ops: Vec<JsOp>,
}

#[derive(Deserialize)]
struct JsOp {
    op: String,
    data: Vec<f64>,
}

impl JsOptions {
    fn to_options(&self) -> Options {
        Options {
            max_randomness_offset: self.max_randomness_offset,
            roughness: self.roughness,
            bowing: self.bowing,
            stroke_width: self.stroke_width,
            curve_tightness: self.curve_tightness,
            curve_fitting: self.curve_fitting,
            curve_step_count: self.curve_step_count,
            fill_style: match self.fill_style.as_str() {
                "solid" => FillStyle::Solid,
                "zigzag" => FillStyle::ZigZag,
                "cross-hatch" => FillStyle::CrossHatch,
                "dots" => FillStyle::Dots,
                "dashed" => FillStyle::Dashed,
                "zigzag-line" => FillStyle::ZigZagLine,
                _ => FillStyle::Hachure,
            },
            fill_weight: self.fill_weight,
            hachure_angle: self.hachure_angle,
            hachure_gap: self.hachure_gap,
            dash_offset: self.dash_offset,
            dash_gap: self.dash_gap,
            zigzag_offset: self.zigzag_offset,
            // The fixture carries the JS number; `as i32` reproduces ToInt32, which is
            // what Math.imul would have applied.
            seed: self.seed as i32,
            disable_multi_stroke: self.disable_multi_stroke,
            disable_multi_stroke_fill: self.disable_multi_stroke_fill,
            preserve_vertices: self.preserve_vertices,
            fill_shape_roughness_gain: self.fill_shape_roughness_gain,
            filled: self.fill.is_some(),
        }
    }
}

// ---------------------------------------------------------------------------
// Running a case
// ---------------------------------------------------------------------------

fn nums(v: &serde_json::Value) -> Vec<f64> {
    v.as_array()
        .expect("args is an array")
        .iter()
        .map(|n| n.as_f64().expect("arg is a number"))
        .collect()
}

fn points(v: &serde_json::Value) -> Vec<[f64; 2]> {
    v.as_array()
        .expect("args is an array")
        .iter()
        .map(|p| {
            let xy = p.as_array().expect("point is an array");
            [
                xy[0].as_f64().expect("x is a number"),
                xy[1].as_f64().expect("y is a number"),
            ]
        })
        .collect()
}

fn polygons(v: &serde_json::Value) -> Vec<Vec<[f64; 2]>> {
    v.as_array()
        .expect("polygon list")
        .iter()
        .map(points)
        .collect()
}

fn run(
    func: &str,
    args: &serde_json::Value,
    options: &JsOptions,
    params: Option<&JsEllipseParams>,
    segs: Option<&Vec<JsSegment>>,
) -> Vec<OpSet> {
    let o = options.to_options();

    // The generator owns its own Ctx: it is the thing that establishes the
    // outline-then-fill random ordering, so it must not be handed a pre-warmed one.
    match func {
        "gen.rectangle" => {
            let a = nums(args);
            return generator::rectangle(a[0], a[1], a[2], a[3], o).sets;
        }
        "gen.ellipse" => {
            let a = nums(args);
            return generator::ellipse(a[0], a[1], a[2], a[3], o).sets;
        }
        "gen.line" => {
            let a = nums(args);
            return generator::line(a[0], a[1], a[2], a[3], o).sets;
        }
        "gen.polygon" => return generator::polygon(&points(args), o).sets,
        "gen.linearPath" => return generator::linear_path(&points(args), o).sets,
        "gen.curve" => return generator::curve(&points(args), o).sets,
        _ => {}
    }

    let mut c = Ctx::new(o);
    vec![match func {
        "rectangle" => {
            let a = nums(args);
            renderer::rectangle(a[0], a[1], a[2], a[3], &mut c)
        }
        "ellipse" => {
            let a = nums(args);
            renderer::ellipse(a[0], a[1], a[2], a[3], &mut c)
        }
        "line" => {
            let a = nums(args);
            renderer::line(a[0], a[1], a[2], a[3], &mut c)
        }
        "polygon" => renderer::polygon(&points(args), &mut c),
        "linearPath" => renderer::linear_path(&points(args), false, &mut c),
        "curve" => renderer::curve(&points(args), &mut c),
        "solidFillPolygon" => renderer::solid_fill_polygon(&polygons(args), &mut c),
        "svgPath" => {
            let js = segs.expect("an svgPath case carries its normalized segments");
            renderer::svg_path(&segments(js), &mut c)
        }
        "patternFillPolygons" => {
            draw_rough::fillers::pattern_fill_polygons(&polygons(args), &mut c)
        }
        "ellipseWithParams" => {
            let a = nums(args);
            let p = renderer::generate_ellipse_params(a[2], a[3], &mut c);

            // The params are part of the contract, not just an intermediate: a
            // pattern-filled ellipse shares them between outline and fill, so a drift
            // here would misalign the two long before the outline looked wrong.
            if let Some(want) = params {
                for (got, want, name) in [
                    (p.increment, want.increment, "increment"),
                    (p.rx, want.rx, "rx"),
                    (p.ry, want.ry, "ry"),
                ] {
                    assert!(
                        (got - want).abs() <= TOLERANCE,
                        "ellipse param {name}: got {got}, want {want}"
                    );
                }
            }
            renderer::ellipse_with_params(a[0], a[1], &mut c, p).0
        }
        other => panic!("fixture uses an unported function: {other}"),
    }]
}

fn opset_kind(s: &str) -> OpSetKind {
    match s {
        "path" => OpSetKind::Path,
        "fillPath" => OpSetKind::FillPath,
        "fillSketch" => OpSetKind::FillSketch,
        other => panic!("unknown op set type {other}"),
    }
}

fn label(func: &str, o: &JsOptions, args: &serde_json::Value) -> String {
    let args = args.to_string();
    let args = if args.len() > 120 {
        format!("{}…", &args[..120])
    } else {
        args
    };
    format!(
        "{func} seed={} roughness={} fill={} sw={} args={args}",
        o.seed, o.roughness, o.fill_style, o.stroke_width
    )
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn matches_roughjs_op_for_op() {
    let fixture: CuratedFixture = serde_json::from_str(include_str!("fixtures/curated.json"))
        .expect("curated fixture parses");
    assert_eq!(
        fixture.roughjs, "4.6.4",
        "fixtures were generated against a different rough.js than the port targets"
    );

    let mut worst_drift = 0.0f64;
    let mut worst_case = String::new();
    let mut drift_by_fn: BTreeMap<String, f64> = BTreeMap::new();

    let mut ops = 0usize;

    for case in &fixture.cases {
        let got = run(
            &case.func,
            &case.args,
            &case.options,
            case.params.as_ref(),
            case.segments.as_ref(),
        );
        let want = case.expected();
        let what = label(&case.func, &case.options, &case.args);

        // The number of op sets is itself a claim: a filled shape must yield fill then
        // outline, an unfilled one only the outline.
        assert_eq!(
            got.len(),
            want.len(),
            "op set count differs for {what}: got {}, want {}",
            got.len(),
            want.len()
        );

        for (si, (gset, wset)) in got.iter().zip(want.iter()).enumerate() {
            assert_eq!(
                gset.kind,
                opset_kind(&wset.kind),
                "set {si} type differs for {what}"
            );

            // Structure first, so a shape error never presents as a confusing numeric one.
            assert_eq!(
                gset.ops.len(),
                wset.ops.len(),
                "set {si} op count differs for {what}: got {}, want {}",
                gset.ops.len(),
                wset.ops.len()
            );

            for (i, (g, w)) in gset.ops.iter().zip(wset.ops.iter()).enumerate() {
                assert_eq!(g.kind(), w.op, "set {si} op {i} kind differs for {what}");
                assert_eq!(
                    g.data().len(),
                    w.data.len(),
                    "set {si} op {i} operand count differs for {what}"
                );

                for (j, (gv, wv)) in g.data().iter().zip(w.data.iter()).enumerate() {
                    let drift = (gv - wv).abs();
                    if drift > worst_drift {
                        worst_drift = drift;
                        worst_case = format!("{what} set {si} op {i} operand {j}");
                    }
                    let worst = drift_by_fn.entry(case.func.clone()).or_insert(0.0);
                    *worst = worst.max(drift);

                    assert!(
                        drift <= TOLERANCE,
                        "set {si} op {i} operand {j} differs for {what}: \
                         got {gv}, want {wv} (drift {drift:e})"
                    );
                }
            }
            ops += gset.ops.len();
        }
    }

    println!(
        "op-for-op: {} cases / {ops} ops against rough.js {}",
        fixture.cases.len(),
        fixture.roughjs
    );
    for (func, drift) in &drift_by_fn {
        println!("  {func:<20} worst drift {drift:e}");
    }
    println!("  worst overall {worst_drift:e} at {worst_case}");
}

/// FNV-1a over the op-kind letters, matching the generator's `fnv1a`.
fn kind_hash(ops: &[Op]) -> u32 {
    let mut h: u32 = 0x811c_9dc5;
    for op in ops {
        let letter = match op {
            Op::Move(_) => b'm',
            Op::LineTo(_) => b'l',
            Op::BCurveTo(_) => b'b',
        };
        h ^= u32::from(letter);
        h = h.wrapping_mul(0x0100_0193);
    }
    h
}

fn close_relative(got: f64, want: f64, scale: f64) -> bool {
    let allowed = RELATIVE_TOLERANCE * scale.abs().max(1.0);
    (got - want).abs() <= allowed
}

#[test]
fn matches_roughjs_across_the_sweep() {
    let fixture: SweepFixture =
        serde_json::from_str(include_str!("fixtures/sweep.summary.json")).expect("sweep parses");
    assert_eq!(fixture.roughjs, "4.6.4");

    let mut total_ops = 0usize;
    let mut by_fn: BTreeMap<String, usize> = BTreeMap::new();

    for case in &fixture.cases {
        let got = run(
            &case.func,
            &case.args,
            &case.options,
            case.params.as_ref(),
            case.segments.as_ref(),
        );
        let want = &case.summary;
        let what = label(&case.func, &case.options, &case.args);

        assert_eq!(
            got.len(),
            want.len(),
            "op set count differs for {what}: got {}, want {}",
            got.len(),
            want.len()
        );

        for (si, (gset, wsum)) in got.iter().zip(want.iter()).enumerate() {
            assert_eq!(
                gset.kind,
                opset_kind(&wsum.kind),
                "set {si} type differs for {what}"
            );
            assert_eq!(
                gset.ops.len(),
                wsum.op_count,
                "set {si} op count differs for {what}: got {}, want {}",
                gset.ops.len(),
                wsum.op_count
            );
            assert_eq!(
                kind_hash(&gset.ops),
                wsum.kind_hash,
                "set {si} op kind sequence differs for {what}"
            );

            let mut sum = 0.0;
            let mut sum_abs = 0.0;
            let mut max_abs = 0.0f64;
            for op in &gset.ops {
                for v in op.data() {
                    sum += v;
                    sum_abs += v.abs();
                    max_abs = max_abs.max(v.abs());
                }
            }

            // `sum` can cancel to near zero, so it is scaled by `sum_abs` — the
            // magnitude the error actually accumulated over — rather than by itself.
            assert!(
                close_relative(sum, wsum.sum, wsum.sum_abs),
                "set {si} coordinate sum differs for {what}: got {sum}, want {}",
                wsum.sum
            );
            assert!(
                close_relative(sum_abs, wsum.sum_abs, wsum.sum_abs),
                "set {si} magnitude sum differs for {what}: got {sum_abs}, want {}",
                wsum.sum_abs
            );
            assert!(
                close_relative(max_abs, wsum.max_abs, wsum.max_abs),
                "set {si} largest coordinate differs for {what}: got {max_abs}, want {}",
                wsum.max_abs
            );

            total_ops += gset.ops.len();
        }
        *by_fn.entry(case.func.clone()).or_insert(0) += 1;
    }

    println!(
        "sweep: {} cases / {total_ops} ops against rough.js {}",
        fixture.cases.len(),
        fixture.roughjs
    );
    for (func, n) in &by_fn {
        println!("  {func:<20} {n} cases");
    }
}

/// The op enum must round-trip the JS `data` lengths, or the comparisons above would be
/// comparing truncated operand lists and passing for the wrong reason.
#[test]
fn op_operand_counts_match_js() {
    assert_eq!(Op::Move([0.0; 2]).data().len(), 2);
    assert_eq!(Op::LineTo([0.0; 2]).data().len(), 2);
    assert_eq!(Op::BCurveTo([0.0; 6]).data().len(), 6);
}
