//! Replays rough.js's own output against the Rust port.
//!
//! Fixtures are generated by `engine/tools/rough-oracle` from roughjs 4.6.4 — the exact
//! version Excalidraw pins — and committed, so this test needs neither Node nor a
//! network. Regenerate with `npm install && npm run generate` in that directory, which
//! you should only ever need to do when the pin in `scripts/oracle-sha.txt` moves.
//!
//! # The bar
//!
//! - **Structure is exact.** Same number of op sets, same op kinds, same order, same
//!   operand counts. A mismatch here is a logic error, never a rounding one.
//! - **Coordinates within `1e-9`.** `+ - * /` and `sqrt` are exactly specified by
//!   IEEE-754 and agree bit-for-bit between V8 and Rust; `sin`, `cos` and friends are
//!   not, and may differ in the last ulp. At 1e-9 world units that is invisible at any
//!   zoom, and the test reports the worst observed drift so regressions in the *margin*
//!   are visible before they become failures.

use std::collections::BTreeMap;

use draw_rough::ops::{Op, OpSet, OpSetKind};
use draw_rough::options::{Ctx, FillStyle, Options};
use draw_rough::renderer;
use serde::Deserialize;

/// Coordinates may differ only by transcendental last-ulp error.
const TOLERANCE: f64 = 1e-9;

#[derive(Deserialize)]
struct Fixture {
    roughjs: String,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    #[serde(rename = "fn")]
    func: String,
    args: serde_json::Value,
    options: JsOptions,
    opset: JsOpSet,
    #[serde(default)]
    params: Option<JsEllipseParams>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct JsOptions {
    max_randomness_offset: f64,
    roughness: f64,
    bowing: f64,
    stroke_width: f64,
    curve_tightness: f64,
    curve_fitting: f64,
    curve_step_count: f64,
    fill_style: String,
    fill_weight: f64,
    hachure_angle: f64,
    hachure_gap: f64,
    dash_offset: f64,
    dash_gap: f64,
    zigzag_offset: f64,
    seed: i64,
    disable_multi_stroke: bool,
    disable_multi_stroke_fill: bool,
    preserve_vertices: bool,
    fill_shape_roughness_gain: f64,
}

#[derive(Deserialize)]
struct JsEllipseParams {
    increment: f64,
    rx: f64,
    ry: f64,
}

#[derive(Deserialize)]
struct JsOpSet {
    #[serde(rename = "type")]
    kind: String,
    ops: Vec<JsOp>,
}

#[derive(Deserialize)]
struct JsOp {
    op: String,
    data: Vec<f64>,
}

impl JsOptions {
    fn to_options(&self) -> Options {
        Options {
            max_randomness_offset: self.max_randomness_offset,
            roughness: self.roughness,
            bowing: self.bowing,
            stroke_width: self.stroke_width,
            curve_tightness: self.curve_tightness,
            curve_fitting: self.curve_fitting,
            curve_step_count: self.curve_step_count,
            fill_style: match self.fill_style.as_str() {
                "solid" => FillStyle::Solid,
                "zigzag" => FillStyle::ZigZag,
                "cross-hatch" => FillStyle::CrossHatch,
                "dots" => FillStyle::Dots,
                "dashed" => FillStyle::Dashed,
                "zigzag-line" => FillStyle::ZigZagLine,
                _ => FillStyle::Hachure,
            },
            fill_weight: self.fill_weight,
            hachure_angle: self.hachure_angle,
            hachure_gap: self.hachure_gap,
            dash_offset: self.dash_offset,
            dash_gap: self.dash_gap,
            zigzag_offset: self.zigzag_offset,
            // The fixture carries the JS number; `as i32` reproduces ToInt32, which is
            // what Math.imul would have applied.
            seed: self.seed as i32,
            disable_multi_stroke: self.disable_multi_stroke,
            disable_multi_stroke_fill: self.disable_multi_stroke_fill,
            preserve_vertices: self.preserve_vertices,
            fill_shape_roughness_gain: self.fill_shape_roughness_gain,
            filled: false,
        }
    }
}

fn nums(v: &serde_json::Value) -> Vec<f64> {
    v.as_array()
        .expect("args is an array")
        .iter()
        .map(|n| n.as_f64().expect("arg is a number"))
        .collect()
}

fn points(v: &serde_json::Value) -> Vec<[f64; 2]> {
    v.as_array()
        .expect("args is an array")
        .iter()
        .map(|p| {
            let xy = p.as_array().expect("point is an array");
            [
                xy[0].as_f64().expect("x is a number"),
                xy[1].as_f64().expect("y is a number"),
            ]
        })
        .collect()
}

/// Runs one case through the Rust port.
fn run(case: &Case) -> OpSet {
    let mut c = Ctx::new(case.options.to_options());
    match case.func.as_str() {
        "rectangle" => {
            let a = nums(&case.args);
            renderer::rectangle(a[0], a[1], a[2], a[3], &mut c)
        }
        "ellipse" => {
            let a = nums(&case.args);
            renderer::ellipse(a[0], a[1], a[2], a[3], &mut c)
        }
        "line" => {
            let a = nums(&case.args);
            renderer::line(a[0], a[1], a[2], a[3], &mut c)
        }
        "polygon" => renderer::polygon(&points(&case.args), &mut c),
        "linearPath" => renderer::linear_path(&points(&case.args), false, &mut c),
        "curve" => renderer::curve(&points(&case.args), &mut c),
        "solidFillPolygon" => {
            let polys: Vec<Vec<[f64; 2]>> = case
                .args
                .as_array()
                .expect("polygon list")
                .iter()
                .map(points)
                .collect();
            renderer::solid_fill_polygon(&polys, &mut c)
        }
        "ellipseWithParams" => {
            let a = nums(&case.args);
            let p = renderer::generate_ellipse_params(a[2], a[3], &mut c);

            // The params are part of the contract, not just an intermediate: a
            // pattern-filled ellipse shares them between outline and fill, so a drift
            // here would misalign the two long before the outline looked wrong.
            if let Some(want) = &case.params {
                for (got, want, name) in [
                    (p.increment, want.increment, "increment"),
                    (p.rx, want.rx, "rx"),
                    (p.ry, want.ry, "ry"),
                ] {
                    assert!(
                        (got - want).abs() <= TOLERANCE,
                        "ellipse param {name}: got {got}, want {want}"
                    );
                }
            }
            renderer::ellipse_with_params(a[0], a[1], &mut c, p).0
        }
        other => panic!("fixture uses an unported function: {other}"),
    }
}

/// Describes a case tersely enough to act on without opening the fixture.
fn label(case: &Case) -> String {
    format!(
        "{} seed={} roughness={} args={}",
        case.func, case.options.seed, case.options.roughness, case.args
    )
}

#[test]
fn matches_roughjs() {
    let raw = include_str!("fixtures/renderer.json");
    let fixture: Fixture = serde_json::from_str(raw).expect("fixture parses");
    assert_eq!(
        fixture.roughjs, "4.6.4",
        "fixtures were generated against a different rough.js than the port targets"
    );

    let mut worst_drift = 0.0f64;
    let mut worst_case = String::new();
    // Drift per function, so a regression points at the guilty transcription.
    let mut drift_by_fn: BTreeMap<String, f64> = BTreeMap::new();

    for case in &fixture.cases {
        let got = run(case);
        let want = &case.opset;
        let what = label(case);

        let want_kind = match want.kind.as_str() {
            "path" => OpSetKind::Path,
            "fillPath" => OpSetKind::FillPath,
            "fillSketch" => OpSetKind::FillSketch,
            other => panic!("unknown op set type {other}"),
        };
        assert_eq!(got.kind, want_kind, "op set type differs for {what}");

        // Structure is checked before coordinates so a shape error never presents as a
        // confusing numeric one.
        assert_eq!(
            got.ops.len(),
            want.ops.len(),
            "op count differs for {what}: got {}, want {}",
            got.ops.len(),
            want.ops.len()
        );

        for (i, (g, w)) in got.ops.iter().zip(want.ops.iter()).enumerate() {
            assert_eq!(g.kind(), w.op, "op {i} kind differs for {what}");
            assert_eq!(
                g.data().len(),
                w.data.len(),
                "op {i} operand count differs for {what}"
            );

            for (j, (gv, wv)) in g.data().iter().zip(w.data.iter()).enumerate() {
                let drift = (gv - wv).abs();
                if drift > worst_drift {
                    worst_drift = drift;
                    worst_case = format!("{what} op {i} operand {j}");
                }
                let worst = drift_by_fn.entry(case.func.clone()).or_insert(0.0);
                *worst = worst.max(drift);

                assert!(
                    drift <= TOLERANCE,
                    "op {i} operand {j} differs for {what}: got {gv}, want {wv} (drift {drift:e})"
                );
            }
        }
    }

    let ops: usize = fixture.cases.iter().map(|c| c.opset.ops.len()).sum();
    println!(
        "matched {} cases / {ops} ops against rough.js {}",
        fixture.cases.len(),
        fixture.roughjs
    );
    for (func, drift) in &drift_by_fn {
        println!("  {func:<18} worst drift {drift:e}");
    }
    println!("  worst overall {worst_drift:e} at {worst_case}");
}

/// The op enum must round-trip the JS `data` lengths, or the comparison above would be
/// comparing truncated operand lists and passing for the wrong reason.
#[test]
fn op_operand_counts_match_js() {
    assert_eq!(Op::Move([0.0; 2]).data().len(), 2);
    assert_eq!(Op::LineTo([0.0; 2]).data().len(), 2);
    assert_eq!(Op::BCurveTo([0.0; 6]).data().len(), 6);
}
